### PR TITLE
Take2

### PR DESCRIPTION
**Pull request by charles-turner-1**
This PR relaxes requirements, allowing for Intake Take2.

Necessary to avoid dependency conflicts.

### CODE REVIEW

**Comment by marc-white** [comment]
What's the correct process for getting the right version of `intake-esm` in for testing?

**Comment by charles-turner-1** [comment]
With the relaxed versioning, you should be able to just `pip install intake>=2.0.0` in the environment.

I'm happy to add a tox config like we have for access-nri-intake-catalog too to automate the testing against 0.7 & 2.0 if you think that would be more robust?

**Comment by marc-white** [comment]
The issue isn't `intake`, it's `intake-esm`. That has requirements that lock `intake` to `<2`, so I need to grab whichever version of `intake-esm` you have onboard to relax that requirement.

**Comment by charles-turner-1** [comment]
Ahhh, of course - I'll add a toxfile to run the tests with that version of intake-esm.

**Comment by marc-white** [comment]
Awesomesauce. We can always remove the `tox` once we're satisfied that the changeover is good and/or `intake` v1 is finally killed.

**Comment by charles-turner-1** [comment]
You should now be able to run the tests against intake>=2.0.0 just by calling `$ tox`

**Comment by marc-white** [comment]
Tox tests are passing OK, so I'm happy.

**Review by marc-white — APPROVED** [review]

**Comment by charles-turner-1** [comment]
@dougiesquire Whilst you're at it could you add Marc as an admin here too?

**Review by rbeucher — APPROVED** [review]

**Comment by rbeucher** [comment]
Great, thanks for doing this @charles-turner-1

**Comment by dougiesquire** [comment]
> @dougiesquire Whilst you're at it could you add Marc as an admin here too?

I've made you both admin

**Comment by charles-turner-1** [comment]
Cross linking to #62 for posterity. Seems that broken tests with take2 dependency were fixed at some point by upstream changes.

**Pull request merged**
